parameters:
    database_driver: %env.database_driver%
    database_host: %env.database_host%
    database_port: %env.database_port%
    database_name: %env.database_name%
    database_user: %env.database_user%
    database_password: %env.database_password%

    database_driver: pdo_mysql
    database_path: ""
    database_table_prefix: wallabag_

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en

    # A secret key that's used to generate certain security-related tokens
    secret:            %env.salt%

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_confirmation: true

    from_email: no-reply@wallabag.org
